// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/GroVlAn/auth-user/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// newMockrepo creates a new instance of mockrepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockrepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockrepo {
	mock := &mockrepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockrepo is an autogenerated mock type for the repo type
type mockrepo struct {
	mock.Mock
}

type mockrepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockrepo) EXPECT() *mockrepo_Expecter {
	return &mockrepo_Expecter{mock: &_m.Mock}
}

// BanUser provides a mock function for the type mockrepo
func (_mock *mockrepo) BanUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_BanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanUser'
type mockrepo_BanUser_Call struct {
	*mock.Call
}

// BanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockrepo_Expecter) BanUser(ctx interface{}, userID interface{}) *mockrepo_BanUser_Call {
	return &mockrepo_BanUser_Call{Call: _e.mock.On("BanUser", ctx, userID)}
}

func (_c *mockrepo_BanUser_Call) Run(run func(ctx context.Context, userID string)) *mockrepo_BanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_BanUser_Call) Return(err error) *mockrepo_BanUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_BanUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *mockrepo_BanUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type mockrepo
func (_mock *mockrepo) Create(ctx context.Context, user domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockrepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *mockrepo_Expecter) Create(ctx interface{}, user interface{}) *mockrepo_Create_Call {
	return &mockrepo_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *mockrepo_Create_Call) Run(run func(ctx context.Context, user domain.User)) *mockrepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_Create_Call) Return(err error) *mockrepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_Create_Call) RunAndReturn(run func(ctx context.Context, user domain.User) error) *mockrepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInactiveUser provides a mock function for the type mockrepo
func (_mock *mockrepo) DeleteInactiveUser(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInactiveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_DeleteInactiveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInactiveUser'
type mockrepo_DeleteInactiveUser_Call struct {
	*mock.Call
}

// DeleteInactiveUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockrepo_Expecter) DeleteInactiveUser(ctx interface{}) *mockrepo_DeleteInactiveUser_Call {
	return &mockrepo_DeleteInactiveUser_Call{Call: _e.mock.On("DeleteInactiveUser", ctx)}
}

func (_c *mockrepo_DeleteInactiveUser_Call) Run(run func(ctx context.Context)) *mockrepo_DeleteInactiveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockrepo_DeleteInactiveUser_Call) Return(err error) *mockrepo_DeleteInactiveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_DeleteInactiveUser_Call) RunAndReturn(run func(ctx context.Context) error) *mockrepo_DeleteInactiveUser_Call {
	_c.Call.Return(run)
	return _c
}

// Exist provides a mock function for the type mockrepo
func (_mock *mockrepo) Exist(ctx context.Context, userQuery domain.UserQuery) (bool, error) {
	ret := _mock.Called(ctx, userQuery)

	if len(ret) == 0 {
		panic("no return value specified for Exist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserQuery) (bool, error)); ok {
		return returnFunc(ctx, userQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserQuery) bool); ok {
		r0 = returnFunc(ctx, userQuery)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserQuery) error); ok {
		r1 = returnFunc(ctx, userQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_Exist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exist'
type mockrepo_Exist_Call struct {
	*mock.Call
}

// Exist is a helper method to define mock.On call
//   - ctx context.Context
//   - userQuery domain.UserQuery
func (_e *mockrepo_Expecter) Exist(ctx interface{}, userQuery interface{}) *mockrepo_Exist_Call {
	return &mockrepo_Exist_Call{Call: _e.mock.On("Exist", ctx, userQuery)}
}

func (_c *mockrepo_Exist_Call) Run(run func(ctx context.Context, userQuery domain.UserQuery)) *mockrepo_Exist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserQuery
		if args[1] != nil {
			arg1 = args[1].(domain.UserQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_Exist_Call) Return(b bool, err error) *mockrepo_Exist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockrepo_Exist_Call) RunAndReturn(run func(ctx context.Context, userQuery domain.UserQuery) (bool, error)) *mockrepo_Exist_Call {
	_c.Call.Return(run)
	return _c
}

// InactivateUser provides a mock function for the type mockrepo
func (_mock *mockrepo) InactivateUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InactivateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_InactivateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InactivateUser'
type mockrepo_InactivateUser_Call struct {
	*mock.Call
}

// InactivateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockrepo_Expecter) InactivateUser(ctx interface{}, userID interface{}) *mockrepo_InactivateUser_Call {
	return &mockrepo_InactivateUser_Call{Call: _e.mock.On("InactivateUser", ctx, userID)}
}

func (_c *mockrepo_InactivateUser_Call) Run(run func(ctx context.Context, userID string)) *mockrepo_InactivateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_InactivateUser_Call) Return(err error) *mockrepo_InactivateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_InactivateUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *mockrepo_InactivateUser_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreUser provides a mock function for the type mockrepo
func (_mock *mockrepo) RestoreUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_RestoreUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreUser'
type mockrepo_RestoreUser_Call struct {
	*mock.Call
}

// RestoreUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockrepo_Expecter) RestoreUser(ctx interface{}, userID interface{}) *mockrepo_RestoreUser_Call {
	return &mockrepo_RestoreUser_Call{Call: _e.mock.On("RestoreUser", ctx, userID)}
}

func (_c *mockrepo_RestoreUser_Call) Run(run func(ctx context.Context, userID string)) *mockrepo_RestoreUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_RestoreUser_Call) Return(err error) *mockrepo_RestoreUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_RestoreUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *mockrepo_RestoreUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnbanUser provides a mock function for the type mockrepo
func (_mock *mockrepo) UnbanUser(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_UnbanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnbanUser'
type mockrepo_UnbanUser_Call struct {
	*mock.Call
}

// UnbanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *mockrepo_Expecter) UnbanUser(ctx interface{}, userID interface{}) *mockrepo_UnbanUser_Call {
	return &mockrepo_UnbanUser_Call{Call: _e.mock.On("UnbanUser", ctx, userID)}
}

func (_c *mockrepo_UnbanUser_Call) Run(run func(ctx context.Context, userID string)) *mockrepo_UnbanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_UnbanUser_Call) Return(err error) *mockrepo_UnbanUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_UnbanUser_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *mockrepo_UnbanUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type mockrepo
func (_mock *mockrepo) UpdatePassword(ctx context.Context, userID string, newPasswordHash string) error {
	ret := _mock.Called(ctx, userID, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockrepo_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type mockrepo_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - newPasswordHash string
func (_e *mockrepo_Expecter) UpdatePassword(ctx interface{}, userID interface{}, newPasswordHash interface{}) *mockrepo_UpdatePassword_Call {
	return &mockrepo_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, newPasswordHash)}
}

func (_c *mockrepo_UpdatePassword_Call) Run(run func(ctx context.Context, userID string, newPasswordHash string)) *mockrepo_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockrepo_UpdatePassword_Call) Return(err error) *mockrepo_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockrepo_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, userID string, newPasswordHash string) error) *mockrepo_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type mockrepo
func (_mock *mockrepo) User(ctx context.Context, userQuery domain.UserQuery) (domain.User, error) {
	ret := _mock.Called(ctx, userQuery)

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserQuery) (domain.User, error)); ok {
		return returnFunc(ctx, userQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserQuery) domain.User); ok {
		r0 = returnFunc(ctx, userQuery)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserQuery) error); ok {
		r1 = returnFunc(ctx, userQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type mockrepo_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
//   - ctx context.Context
//   - userQuery domain.UserQuery
func (_e *mockrepo_Expecter) User(ctx interface{}, userQuery interface{}) *mockrepo_User_Call {
	return &mockrepo_User_Call{Call: _e.mock.On("User", ctx, userQuery)}
}

func (_c *mockrepo_User_Call) Run(run func(ctx context.Context, userQuery domain.UserQuery)) *mockrepo_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserQuery
		if args[1] != nil {
			arg1 = args[1].(domain.UserQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_User_Call) Return(user domain.User, err error) *mockrepo_User_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockrepo_User_Call) RunAndReturn(run func(ctx context.Context, userQuery domain.UserQuery) (domain.User, error)) *mockrepo_User_Call {
	_c.Call.Return(run)
	return _c
}

// UserInfo provides a mock function for the type mockrepo
func (_mock *mockrepo) UserInfo(ctx context.Context, userQuery domain.UserQuery) (domain.UserInfo, error) {
	ret := _mock.Called(ctx, userQuery)

	if len(ret) == 0 {
		panic("no return value specified for UserInfo")
	}

	var r0 domain.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserQuery) (domain.UserInfo, error)); ok {
		return returnFunc(ctx, userQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserQuery) domain.UserInfo); ok {
		r0 = returnFunc(ctx, userQuery)
	} else {
		r0 = ret.Get(0).(domain.UserInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserQuery) error); ok {
		r1 = returnFunc(ctx, userQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockrepo_UserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserInfo'
type mockrepo_UserInfo_Call struct {
	*mock.Call
}

// UserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userQuery domain.UserQuery
func (_e *mockrepo_Expecter) UserInfo(ctx interface{}, userQuery interface{}) *mockrepo_UserInfo_Call {
	return &mockrepo_UserInfo_Call{Call: _e.mock.On("UserInfo", ctx, userQuery)}
}

func (_c *mockrepo_UserInfo_Call) Run(run func(ctx context.Context, userQuery domain.UserQuery)) *mockrepo_UserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserQuery
		if args[1] != nil {
			arg1 = args[1].(domain.UserQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockrepo_UserInfo_Call) Return(userInfo domain.UserInfo, err error) *mockrepo_UserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *mockrepo_UserInfo_Call) RunAndReturn(run func(ctx context.Context, userQuery domain.UserQuery) (domain.UserInfo, error)) *mockrepo_UserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockhasher creates a new instance of mockhasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhasher {
	mock := &mockhasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhasher is an autogenerated mock type for the hasher type
type mockhasher struct {
	mock.Mock
}

type mockhasher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhasher) EXPECT() *mockhasher_Expecter {
	return &mockhasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type mockhasher
func (_mock *mockhasher) Compare(encodedHash string, password string) error {
	ret := _mock.Called(encodedHash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(encodedHash, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockhasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type mockhasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - encodedHash string
//   - password string
func (_e *mockhasher_Expecter) Compare(encodedHash interface{}, password interface{}) *mockhasher_Compare_Call {
	return &mockhasher_Compare_Call{Call: _e.mock.On("Compare", encodedHash, password)}
}

func (_c *mockhasher_Compare_Call) Run(run func(encodedHash string, password string)) *mockhasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockhasher_Compare_Call) Return(err error) *mockhasher_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockhasher_Compare_Call) RunAndReturn(run func(encodedHash string, password string) error) *mockhasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type mockhasher
func (_mock *mockhasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockhasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type mockhasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *mockhasher_Expecter) Hash(password interface{}) *mockhasher_Hash_Call {
	return &mockhasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *mockhasher_Hash_Call) Run(run func(password string)) *mockhasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhasher_Hash_Call) Return(s string, err error) *mockhasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockhasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *mockhasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
