http:
  port: '8082'
  max_header_bytes: 1048576
  read_header_timeout: 10s
  write_timeout: 10s
  base_http_path: '/api/v1/user'

grpc:
  port: '8012'
  access_api_host: 'access'
  access_api_port: '8013'

kafka:
  brokers:
    - 'localhost:7788'
  topic: 'user-role'

settings:
  default_timeout: 15s
  hash_cost: 12

db:
  host: 'user_db'
  port: 5433
  ssl_mode: disable

middleware:
  allowed_origins:
    - 'https://*'
    - 'http://*'
  allowed_methods:
    - 'GET'
    - 'POST'
    - 'PATCH'
    - 'PUT'
    - 'DELETE'
    - 'OPTIONS'
  allowed_headers:
    - 'Accept'
    - 'Authorization'
    - 'Content-Type'
    - 'X-CSRF-Token'
  allow_credentials: true
  max_age: 300
