http:
  port: '8091'
  max_header_bytes: 1048576
  read_header_timeout: 10s
  write_timeout: 10s
  base_http_path: '/api/user'

settings:
  default_timeout: 15s
  hash_cost: 12

db:
  host: 'user_db'
  port: 5433
  ssl_mode: disable
